# Generated by Django 3.1.7 on 2021-04-19 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categor',
            field=models.IntegerField(choices=[(0, 'python'), (1, 'java'), (2, 'c')], default=0, verbose_name='内容分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='illustration',
            field=models.ImageField(null=True, upload_to='images', verbose_name='插图'),
        ),
        migrations.AddField(
            model_name='blog',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_tome',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='匿名', max_length=20, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=20, verbose_name='标题'),
        ),
    ]
